In [1]:
import pandas as pd 
import numpy as np 
from matplotlib import pyplot as plt

In C:\anaconda-3.5.2.0\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle:
The text.latex.unicode rcparam was deprecated in Matplotlib 3.0 and will be removed in 3.2.
In C:\anaconda-3.5.2.0\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle:
The savefig.frameon rcparam was deprecated in Matplotlib 3.1 and will be removed in 3.3.
In C:\anaconda-3.5.2.0\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle:
The pgf.debug rcparam was deprecated in Matplotlib 3.0 and will be removed in 3.2.
In C:\anaconda-3.5.2.0\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle:
The verbose.level rcparam was deprecated in Matplotlib 3.1 and will be removed in 3.3.
In C:\anaconda-3.5.2.0\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle:
The verbose.fileo rcparam was deprecated in Matplotlib 3.1 and will be removed in 3.3.

In [9]:
overall = pd.read_csv('./data/batch1/Cell_Cytoplasm_Intensity_Mean_Ch=1_Img=1.csv', header=2)
overall.head()

,Cell Cytoplasm Intensity Mean,Unit,Category,Channel,Image,Birth [s],Death [s],TrackID,ID,OriginalID,Original Component Name,Original Component ID,Original Image Name,Original Image ID,Unnamed: 14
0,561.208618,NaN,Cell,1,Image 1,0.0,1.0,1000000000,0,0,Cells Unnamed 1 H200911_HEYA8_175_261.icsx_[ib...,400001,H200911_s1.ome,D:\Users\Samuel_T\H200911\FIJI_Stacked_output\...,NaN
1,559.883850,NaN,Cell,1,Image 1,0.0,1.0,1000000109,109,109,Cells Unnamed 1 H200911_HEYA8_175_261.icsx_[ib...,400001,H200911_s1.ome,D:\Users\Samuel_T\H200911\FIJI_Stacked_output\...,NaN
2,566.485229,NaN,Cell,1,Image 1,0.0,1.0,1000000190,190,190,Cells Unnamed 1 H200911_HEYA8_175_261.icsx_[ib...,400001,H200911_s1.ome,D:\Users\Samuel_T\H200911\FIJI_Stacked_output\...,NaN
3,576.011292,NaN,Cell,1,Image 1,0.0,1.0,1000000385,385,385,Cells Unnamed 1 H200911_HEYA8_175_261.icsx_[ib...,400001,H200911_s1.ome,D:\Users\Samuel_T\H200911\FIJI_Stacked_output\...,NaN
4,542.234497,NaN,Cell,1,Image 1,0.0,1.0,1000000474,474,474,Cells Unnamed 1 H200911_HEYA8_175_261.icsx_[ib...,400001,H200911_s1.ome,D:\Users\Samuel_T\H200911\FIJI_Stacked_output\...,NaN